name: Bug Report
description: File a bug report.
labels: "bug"
assignees: "desaxxx"
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting a bug!"
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: Please enter your minecraft version and plugin version.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What is the problem?
      description: Please explain what happened and what was expected to happen.
    validations:
      required: true
  - type: textarea
    id: how-triggered
    attributes:
      label: How do you trigger this bug?
      description: Please explain step by step.
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error Log Output or Screenshots
      description: You can paste your logs or screenshots here.
  - type: checkboxes
    id: terms
    attributes:
      label: Aggrement
      options:
        - label: I have read the guidelines above and affirm them.
          required: true
