name: Feature Request
description: File a feature request.
labels: "enhancement"
assignees: "desaxxx"
body:
  - type: markdown
    attributes:
      value: "Thanks for suggesting a feature!"
  - type: textarea
    id: why-need
    attributes:
      label: Why This Feature?
      description: Please explain why you need this feature. 
    validations:
      required: true
  - type: textarea
    id: what-feature
    attributes:
      label: What is that Feature?
      description: Please explain what is that feature and what exactly it does.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Aggrement
      options:
        - label: I have read the guidelines above and affirm them.
          required: true
